---
title: "Multivariate models"
output: html_document
---

The goals of this lesson are to introduce multivariate ordination analyses.

## Additional Reading
* On the web see [The Ordination Webpage](http://ordination.okstate.edu/).
* Chapters 5 and 6 of *Numerical Ecology with R*. 

Ordination is a term that 

```{r setup, echo=FALSE}
# setup the R enviornment for kniting markdown doc properly
library(knitr)
opts_knit$set(root.dir='../')
```

Table of 
<table cellpadding="0" cellspacing="2">
    <tr>
		<td width="148" style="border: none; padding: 0in">
			<p><font face="Times New Roman, serif"><font size="3" style="font-size: 12pt"><b>Acronym</b></font></font></p>
		</td>
		<td width="150" style="border: none; padding: 0in">
			<p><font face="Times New Roman, serif"><font size="3" style="font-size: 12pt"><b>Name</b>&nbsp;</font></font></p>
		</td>
		<td width="113" style="border: none; padding: 0in">
			<p><font face="Times New Roman, serif"><font size="3" style="font-size: 12pt"><b>type
			of analysis</b></font></font></p>
		</td>
		<td width="124" style="border: none; padding: 0in">
			<p><font face="Times New Roman, serif"><font size="3" style="font-size: 12pt"><b>Algorithm</b>&nbsp;</font></font></p>
		</td>
		<td width="148" style="border: none; padding: 0in">
			<p><font face="Times New Roman, serif"><font size="3" style="font-size: 12pt"><b>R
			function</b></font></font></p>
		</td>
	</tr>
	<tr>
		<td width="97" style="border: none; padding: 0in">
			<p><font face="Times New Roman, serif"><font size="3" style="font-size: 12pt"><i>PCA</i></font></font></p>
		</td>
		<td width="150" style="border: none; padding: 0in">
			<p><font face="Times New Roman, serif"><font size="3" style="font-size: 12pt">Principal
			Components Analysis&nbsp;</font></font></p>
		</td>
		<td width="113" style="border: none; padding: 0in">
			<p><font face="Times New Roman, serif"><font size="3" style="font-size: 12pt">indirect</font></font></p>
		</td>
		<td width="124" style="border: none; padding: 0in">
			<p><font face="Times New Roman, serif"><font size="3" style="font-size: 12pt">Eigenanalysis,
			SVD&nbsp;</font></font></p>
		</td>
		<td width="148" style="border: none; padding: 0in">
			<p><font face="Times New Roman, serif"><font size="3" style="font-size: 12pt">Many</font></font></p>
		</td>
	</tr>
	<tr>
		<td width="97" style="border: none; padding: 0in">
			<p><font face="Times New Roman, serif"><font size="3" style="font-size: 12pt"><i>CA</i></font></font></p>
		</td>
		<td width="150" style="border: none; padding: 0in">
			<p><font face="Times New Roman, serif"><font size="3" style="font-size: 12pt">Correspondence
			Analysis&nbsp;</font></font></p>
		</td>
		<td width="113" style="border: none; padding: 0in">
			<p><font face="Times New Roman, serif"><font size="3" style="font-size: 12pt">indirect</font></font></p>
		</td>
		<td width="124" style="border: none; padding: 0in">
			<p><font face="Times New Roman, serif"><font size="3" style="font-size: 12pt">RA,&nbsp;eigenanalysis,
			SVD&nbsp;</font></font></p>
		</td>
		<td width="148" style="border: none; padding: 0in">
			<p><font face="Times New Roman, serif"><font size="3" style="font-size: 12pt">DECORANA,
			CANOCO, others</font></font></p>
		</td>
	</tr>
	<tr>
		<td width="97" style="border: none; padding: 0in">
			<p><font face="Times New Roman, serif"><font size="3" style="font-size: 12pt"><i>DCA</i></font></font></p>
		</td>
		<td width="150" style="border: none; padding: 0in">
			<p><font face="Times New Roman, serif"><font size="3" style="font-size: 12pt">Detrended
			Correspondence Analysis&nbsp;</font></font></p>
		</td>
		<td width="113" style="border: none; padding: 0in">
			<p><font face="Times New Roman, serif"><font size="3" style="font-size: 12pt">indirect</font></font></p>
		</td>
		<td width="124" style="border: none; padding: 0in">
			<p><font face="Times New Roman, serif"><font size="3" style="font-size: 12pt">RA
			with detrending and rescaling&nbsp;</font></font></p>
		</td>
		<td width="148" style="border: none; padding: 0in">
			<p><font face="Times New Roman, serif"><font size="3" style="font-size: 12pt">DECORANA,
			CANOCO</font></font></p>
		</td>
	</tr>
	<tr>
		<td width="97" style="border: none; padding: 0in">
			<p><font face="Times New Roman, serif"><font size="3" style="font-size: 12pt"><i>CCA&nbsp;</i></font></font></p>
		</td>
		<td width="150" style="border: none; padding: 0in">
			<p><font face="Times New Roman, serif"><font size="3" style="font-size: 12pt">Canonical
			Correspondence Analysis&nbsp;</font></font></p>
		</td>
		<td width="113" style="border: none; padding: 0in">
			<p><font face="Times New Roman, serif"><font size="3" style="font-size: 12pt">direct</font></font></p>
		</td>
		<td width="124" style="border: none; padding: 0in">
			<p><font face="Times New Roman, serif"><font size="3" style="font-size: 12pt">RA
			with regressions,eigenanalysis&nbsp;</font></font></p>
		</td>
		<td width="148" style="border: none; padding: 0in">
			<p><font face="Times New Roman, serif"><font size="3" style="font-size: 12pt">CANOCO</font></font></p>
		</td>
	</tr>
	<tr>
		<td width="97" style="border: none; padding: 0in">
			<p><font face="Times New Roman, serif"><font size="3" style="font-size: 12pt"><i>DCCA</i></font></font></p>
		</td>
		<td width="150" style="border: none; padding: 0in">
			<p><font face="Times New Roman, serif"><font size="3" style="font-size: 12pt">Detrended
			Canonical Correspondence Analysis&nbsp;</font></font></p>
		</td>
		<td width="113" style="border: none; padding: 0in">
			<p><font face="Times New Roman, serif"><font size="3" style="font-size: 12pt">direct</font></font></p>
		</td>
		<td width="124" style="border: none; padding: 0in">
			<p><font face="Times New Roman, serif"><font size="3" style="font-size: 12pt">RA
			with regressions and detrending&nbsp;</font></font></p>
		</td>
		<td width="148" style="border: none; padding: 0in">
			<p><font face="Times New Roman, serif"><font size="3" style="font-size: 12pt">CANOCO</font></font></p>
		</td>
	</tr>
</table>

