---
title: "Shapefiles and Rasters"
author: "Naomi Schwartz and Dan McGlinn"
output: html_document
---

```{r setup, echo=FALSE}
# setup the R enviornment for kniting markdown doc properly
library(knitr)
opts_knit$set(root.dir='../')
```
```{r}
# install.packages(c("maps","sf", "raster"))

library(maps)     # convinient pkg for maps of the world
library(sf)

# First, make some maps. The "maps" package has databases="world","usa","state",
# or "county". (There are also a few for foreign countries like France and
# Italy.) In each database, you can plot any region or group of regions.

world <- map(database="world")
names(world)
head(world$names)
# names in world database can all be plot as a region. For example:
map(database="world", regions=c("Cambodia","Thailand","Vietnam","Laos"))

map(database="state",regions=c("virginia","north carolina","south carolina"))
# you can add cities using map.cities command.

nc_county <- map(database="county",regions="north carolina")
head(nc_county$names)
triangle <- map(database="county",
               regions=c("north carolina,orange","north carolina,wake","north carolina,durham"),
               fill=T, plot=F)
triangle$names

# We can turn a map into a spatial polygons object and fill it with data,
# turning it into a spatial polygon dataframe.

tri_sf <- st_as_sf(triangle)

plot(tri_sf, axes=T)

# add data to make spatial polygons data frame
population <- c(266132, 132272, 892409) 

tri_sf$pop <- population

plot(tri_sf['pop'])

# If your data are in different projections, you need to change the projection
# so that they are all in 
# the same coordinate reference system.

world <- map(database="world", fill=T, plot=F)
world_longlat <- st_as_sf(world) 

# use fucntion spTransform to transform to mercator
world_merc <- st_transform(world_longlat, crs=st_crs("+proj=merc"))
# Lambert Azimuthal Equal Area
world_laea <- st_transform(world_longlat, crs=st_crs("+proj=laea"))
# sinusoidal
world_sinusoidal <- st_transform(world_longlat,
                                 crs=st_crs("+proj=sinu"))

# plot the four together to see the difference. Mercator projection distorts
# area far from the equator. LAEA is accurately represents area but not angles.
# Sinusoidal is equal area and conserves distances along parallels.
par(mfrow=c(1,1))
plot(world_longlat)
plot(world_merc)
plot(world_laea)
plot(world_sinusoidal)

# A four page cheat sheet about coordinate reference systems (CRSs), including
# projections, datums, and coordinate systems, and the use of these in R.
#https://www.nceas.ucsb.edu/sites/default/files/2020-04/OverviewCoordinateReferenceSystems.pdf
# A fun projection link
# http://xkcd.com/977/

# OK, some slightly more complicated stuff. Data from MODIS fire detections in
# the US in 2010.
# metadata for MODIS fire data available at:
# http://firemapper.sc.egov.usda.gov/data/fireptdata/modisfire_2010_conus.htm

fire2010 <- sf::st_read(dsn = './data/MODISfire2010',
                        layer = 'modis_fire_2010_365_conus')

class(fire2010)
names(fire2010)  
st_crs(fire2010)  # retrieves coordinate reference system
dim(fire2010)

# make a map of Julian day of each fire
plot(fire2010["JULIAN"], cex = 0.25)

# get summary statistics for each attribute

summary(fire2010)

# subsetting: select fires that occurred in the last 6 months (days 182 to 365)
# of 2010

fire <- subset(fire2010, JULIAN > 182)
class(fire)
names(fire)
dim(fire)
summary(fire)
plot(fire['JULIAN'], cex = 0.25)

# select the fires in NC. First we'll identify which state each fire occurred
# in, then subset the ones from NC. 
USA <- map(database='state', plot=F, fill=T)
names(USA)
USA$names
USA_sf <- st_as_sf(USA)

# make sure projection of USA polygon is same as fire points
USA_sf <- st_transform(USA_sf, st_crs(fire))

# overlay performs a "point in polygon" operation--meaning that it will return
# us a vector giving the index of which polygon in USA_sp each point in firehot
# is. We then index that to names(USA_sp) to get the name of the state for that
# index.
sf_use_s2(FALSE)
fire_state <- st_intersection(fire, USA_sf)

# Then, subset the ones from NC. We have to use grep because there are actually
# three polygons for NC.
firenc <- fire_state[grep("north carolina", fire_state$ID), ]
dim(firenc)


# make a map of fires by temperature. 
addLegendToSFPlot <- function(values = c(0, 1), labels = c("Low", "High"), 
                              palette = c("blue", "red"), ...){

    # Get the axis limits and calculate size
    axisLimits <- par()$usr
    xLength <- axisLimits[2] - axisLimits[1]
    yLength <- axisLimits[4] - axisLimits[3]

    # Define the colour palette
    colourPalette <- leaflet::colorNumeric(palette, range(values))

    # Add the legend
    plotrix::color.legend(xl=axisLimits[2] - 0.1*xLength, xr=axisLimits[2],
                          yb=axisLimits[3], yt=axisLimits[3] + 0.1 * yLength,
                          legend = labels, rect.col = colourPalette(values), 
                          gradient="y", ...)
}

#First make an NC spatial polygon to put
# around the fire points.

NC <- map(database='state', regions='north carolina', fill=T,
          plot=F)
                            
NC_st <- st_as_sf(NC)
NC_st <- st_transform(NC_st, crs=st_crs(firenc))

cuts <- cut(firenc$JULIAN, 10)
colors <- heat.colors(10)[as.numeric(cuts)] 

plot(st_geometry(NC_st))
plot(st_geometry(firenc['JULIAN']), add = TRUE,
     col = colors, pch = 19, cex = 0.5)


addLegendToSFPlot(values = seq(from = 183, to = 363, length.out = 10), 
                  labels = c("Low", "", "", "", "Medium", "", "", "", "", "High"),
                  palette = heat.colors(10))


# cannot figure out how to combine in ggplot nicely. 
#ggplot(NC_st) + geom_sf()
#ggplot(firenc['JULIAN']) + geom_sf() 
#geom_point(st_geometry(firenc['JULIAN']))

# for the last step, let's export this as a KML (readable by google earth) using
# write OGR and plot the locations of fires in NC in google earth. The first
# argument is the object we want to export, the second is the filename (by
# default it will go in our working directory), the layer we want to export, and
# the file format.
write_sf(firenc, "firenctemp.kml", "TEMP", driver="kml")

## Rasters ----------------------------------------
## download Rdata file here:
## https://www.dropbox.com/s/gafxazc9575nf3j/bioclim_10m.Rdata?dl=0
library(raster)

load('./data/bioclim_10m.Rdata')
plot(bioStack, "mat")

?extract

fire_climate <- extract(bioStack, firenc)
class(fire_climate)
head(fire_climate)
nrow(fire_climate)

firenc <- cbind(firenc, fire_climate)
head(firenc)
plot(TEMP ~ ap, data=firenc) 
```

Here is a quick demo of a new R package called `leaflet`

https://rstudio.github.io/leaflet

```{r}
library(leaflet)
mapStates = map("state", fill = TRUE, plot = FALSE)
leaflet(data = mapStates) %>% addTiles() %>%
  addPolygons(fillColor = topo.colors(10, alpha = NULL), stroke = FALSE)
```

```{r}
m <- leaflet(data = firenc) %>% addTiles() %>%
  addCircleMarkers(radius = 2, label = ~as.character(firenc$TEMP))
m %>% addProviderTiles(providers$Esri.NatGeoWorldMap)
```


```{r}
m = leaflet() %>% addTiles()
df = data.frame(
  lat = rnorm(100),
  lng = rnorm(100),
  size = runif(100, 5, 20),
  color = sample(colors(), 100)
)
m = leaflet(df) %>% addTiles()
m %>% addCircleMarkers(radius = ~size, color = ~color, fill = FALSE)
m %>% addCircleMarkers(radius = runif(100, 4, 10), color = c('red'))
```

```{r}
m %>% addProviderTiles(providers$Esri.NatGeoWorldMap)
```
